<?php
/**
 * Created by PhpStorm.
 * User: ivan.li
 * Date: 5/07/2017
 * Time: 9:13 AM
 */

namespace IvanCLI\Parser\Repositories\LAZADA;


use IvanCLI\Parser\Repositories\XPathParser;

class PriceParser extends XPathParser
{
    public function extract()
    {
        parent::extract(); // TODO: Change the autogenerated stub
        foreach ($this->extractions as $index => $extraction) {
            $this->extractions[$index] = number_format(floatval($extraction), 2);
        }
    }
}